apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-node-tuning:tuned
roleRef:
  kind: ClusterRole
  name: cluster-node-tuning:tuned
subjects:
- kind: ServiceAccount
  name: tuned
  namespace: openshift-cluster-node-tuning-operator
userNames:
- system:serviceaccount:openshift-cluster-node-tuning-operator:tuned
