apiVersion: v1
kind: SecurityContextConstraints
metadata:
  annotations:
  name: openshift-cluster-node-tuning
allowHostDirVolumePlugin: true
allowHostNetwork: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
fsGroup:
  type: RunAsAny
groups:
- system:nodes
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:openshift-cluster-node-tuning:tuned
