apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: profiles.tuned.openshift.io
spec:
  group: tuned.openshift.io
  names:
    kind: Profile
    listKind: ProfileList
    plural: profiles
    singular: profile
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      description: Profile is a specification for a Profile resource
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            config:
              properties:
                tunedProfile:
                  description: tuned profile to apply
                  type: string
              required:
              - tunedProfile
              type: object
          required:
          - config
          type: object
        status:
          description: ProfileStatus is the status for a Profile resource
          properties:
            bootcmdline:
              description: kernel parameters calculated by tuned for the active tuned
                profile
              type: string
          type: object
      type: object
