# Account for the operator itself.  It should require namespace scoped
# permissions.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-node-tuning-operator

---

# Cluster role for the operator itself.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-node-tuning-operator
  namespace: openshift-cluster-node-tuning-operator
rules:
- apiGroups:
  - tuned.openshift.io
  resources:
  - tuneds
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - delete
  - create
  - update
- apiGroups:
  - ""
  - rbac.authorization.k8s.io
  resources:
  - namespaces
  - nodes
  - pods
  - serviceaccounts
  - services
  - configmaps
  - clusterroles
  - clusterrolebindings
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  - nodes/spec
  verbs:
  - get

---

# Binds the operator cluster role to its Service Account.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-node-tuning-operator
subjects:
- kind: ServiceAccount
  name: cluster-node-tuning-operator
  namespace: openshift-cluster-node-tuning-operator
roleRef:
  kind: ClusterRole
  name: cluster-node-tuning-operator
  namespace: openshift-cluster-node-tuning-operator
userNames:
- "system:serviceaccount:openshift-cluster-node-tuning-operator:cluster-node-tuning-operator"
