apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: openshift-elasticsearch
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Optimize systems running ES on OpenShift nodes
      include=openshift-node
      [sysctl]
      vm.max_map_count=262144
    name: openshift-elasticsearch
  recommend:
  - match:
    - label: tuned.openshift.io/elasticsearch
      type: pod
    priority: 20
    profile: openshift-elasticsearch
